runtime! debian.vim

if has("syntax")
  syntax on
endif

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

if has("autocmd")
  filetype plugin indent on
endif

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set showmatch
set ignorecase
set hlsearch 
set incsearch
set textwidth=80
set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab
set paste

colorscheme vividchalk
command Tree VTreeExplore


" Funciones exclusivas para Vim
function SetUp()
   28vsplit|silent view ~/.vim/ayuda
   28split
   VTreeExplore
   CD $HOME
   if !exists('t:is_tab')
       wincmd l
       set number
   else
       set number!
       wincmd l
   endif
   let w:created = 1
endfunction


function SetUpNewTab()
    if !exists('w:created')
        let t:is_tab = 1
        call SetUp()
    endif
endfunction

" Llamadas automáticas para Vim
autocmd VimEnter * call SetUp()

" Autocompletado con SuperTab
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"

" Instrucciones exclusivas para PHP
" TODO refactorizar y llevar a archivo externo (plugin)
imap <? <?php<cr><cr>?><left><left><Up>
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd TabEnter * call SetUpNewTab()

